name: Autobump

on:
  release:
    types: [released]   # trigger when release got created (preferred)
  # trigger on tag push
  # push:
  #   tags:
  #     - "*"

jobs:
  autobump:
    name: Autobump Cask
    runs-on: ubuntu-latest

    steps:
      # https://github.com/dawidd6/action-homebrew-bump-formula
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{secrets.GH_TOKEN_HOMEBREW}}
          tap: setchy/atlassify
          formula: atlassify