name: Release App

on:
  push:
    branches:
      - 'release/v**'
  workflow_dispatch: # For manually running release process to verify codesigning of artifacts

permissions:
  contents: write

jobs:
  release-macos:
    name: Publish macOS (electron-builder)
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - run: pnpm make:macos --publish onTagOrDraft
        env:
          APPLE_ID_USERNAME: ${{ secrets.appleid_username }}
          APPLE_ID_PASSWORD: ${{ secrets.appleid_password }}
          APPLE_TEAM_ID: ${{ secrets.appleid_teamid }}
          CSC_LINK: ${{ secrets.csc_link }}
          CSC_KEY_PASSWORD: ${{ secrets.csc_key_password }}
          GH_TOKEN: ${{ secrets.github_token }}
          NOTARIZE: true
      - uses: actions/upload-artifact@v4
        with:
          name: Atlasify-release-mac
          path: dist/
          overwrite: true

  release-windows:
    name: Publish Windows (electron-builder)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - run: pnpm make:win --publish onTagOrDraft
        env:
          GH_TOKEN: ${{ secrets.github_token }}
      - uses: actions/upload-artifact@v4
        with:
          name: Atlasify-release-win
          path: dist/
          overwrite: true

  release-linux:
    name: Publish Linux (electron-builder)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - run: pnpm make:linux --publish onTagOrDraft
        env:
          GH_TOKEN: ${{ secrets.github_token }}
      - uses: actions/upload-artifact@v4
        with:
          name: Atlasify-release-linux
          path: dist/
          overwrite: true